fix:
nvim-tree/nvim-tree.lua pull request #1648
Opened 2022-10-14 23:21 UTC by Almo7aya

fixes #1643

My changes prevent nvim-tree from using already closed window, usually when using floating window mode, more details are in the issue #1643

2022-10-15 00:24 UTC, alex-courtis requested changes
Testing with nvt-min.lua from the issue resulted in an empty nvim-tree window. Upon `R` the contents were correctly repopulated.

[![asciicast](https://asciinema.org/a/528519.svg)](https://asciinema.org/a/528519)

2022-10-15 00:58 UTC, Almo7aya commented
Ummmm, after some digging I found out that I have 
```lua
update_focused_file = {
	enable = true,
},
```
in my config file, when removing it the issue you faced occurs, I'm checking...

You can try this config with my branch and `update_focused_file = true`

```lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvt-min/site]])
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
	require("packer").startup({
		{
			"wbthomason/packer.nvim",
			{
				"almo7aya/nvim-tree.lua",
				branch = "fix/preview_action_on_floating_windows",
			},
			"kyazdani42/nvim-web-devicons",
			-- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
		},
		config = {
			package_root = package_root,
			compile_path = install_path .. "/plugin/packer_compiled.lua",
			display = { non_interactive = true },
		},
	})
end
if vim.fn.isdirectory(install_path) == 0 then
	print("Installing nvim-tree and dependencies.")
	vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
vim.cmd([[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]])
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
	require("nvim-tree").setup({
		update_focused_file = {
			enable = true,
		},
		view = {
			float = {
				enable = true,
			},
		},
	})
end

vim.api.nvim_set_keymap("n", "<Space>e", "<cmd>:NvimTreeToggle<CR>", {})

```

2022-10-15 01:13 UTC, alex-courtis commented
> You can try this config with my branch and `update_focused_file = true`

That works as expected.

2022-10-15 01:20 UTC, Almo7aya commented
seems like 
```lua
  if opts.update_focused_file.enable then
    create_nvim_tree_autocmd("BufEnter", {
      callback = function()
        M.find_file(false)
      end,
    })
  end
```
has something todo with this, removing `M.find_file(false)` results in the same issue you mentioned

2022-10-15 01:28 UTC, alex-courtis commented
Cursory investigation:

It seems that the tree window is being closed during the preview action: https://github.com/Almo7aya/nvim-tree.lua/blob/79f631bc1d52b387f4ae59fad1291d894afa97f5/lua/nvim-tree/actions/node/open-file.lua#L134

Rather than being reactive to the closed window in `focus`, we could keep the floating tree window open.

2022-10-15 03:08 UTC, Almo7aya commented
After a deep debugging sessions, I discovered that we have an option called `view.float.quit_on_focus_loss` which is enabled by default to kill the window when losing focus 
```lua
  if opts.view.float.enable and opts.view.float.quit_on_focus_loss then
    create_nvim_tree_autocmd("WinLeave", { pattern = "NvimTree_*", callback = view.close })
  end
``` 
so ignoring this autocmd on preview fixes the issue

2022-10-15 03:56 UTC, alex-courtis commented
Still blank after preview. The floating window is definitely still being closed. This can be validated via `:echo win_getid()` before and after the preview.

The next call to `set_current_win_no_autocmd` is the one actually causing the WinLeave event to be fired. This could be moved into an else, something like
```lua
  if mode == "preview" then
    -- ignore "WinLeave" autocmd on preview
    -- because the registered "WinLeave"
    -- will kill the floating window immediately
    set_current_win_no_autocmd(api.nvim_get_current_win(), "WinLeave")
  else
    set_current_win_no_autocmd(target_winid)
  end
```

Unfortunately there is another WinLeave event fired after `open_in_new_window`.

2022-10-15 05:06 UTC, Almo7aya commented
I was calling `set_current_win_no_autocmd ` with the wrong window id, I adjust it now, I can't replicate the blank window after preview

2022-10-15 05:08 UTC, alex-courtis commented
> I was calling `set_current_win_no_autocmd ` with the wrong window id, I adjust it now, I can't replicate the blank window after preview

Nice work. I'm out of time today, I'll take it for a drive tomorrow.

2022-10-16 00:49 UTC, alex-courtis commented on lua/nvim-tree/view.lua
> +  if not a.nvim_win_is_valid(wnr) then
I don't think we need this any more.

I tested successfully without these changes.

2022-10-16 00:52 UTC, alex-courtis commented on lua/nvim-tree/actions/node/open-file.lua
> +  if mode == "preview" then
This is correct, however is only desirable for floating windows. There may be (future) WinLeave events in the non-floating case that we still wish to receive.

- [ ] Please change to `if mode == "preview" and view float is set then`

2022-10-16 00:58 UTC, alex-courtis requested changes
Tested OK with open-file changes only:

- [ ] float enabled
- [ ] float disabled
- [ ] filter visible
- [ ] quit_on_focus_lost disabled

2022-10-16 01:17 UTC, merged

2022-10-16 01:17 UTC, alex-courtis commented
Thank you so much for this fix!