Sync nvim-tree across tabs
nvim-tree/nvim-tree.lua pull request #1662
Opened 2022-10-16 10:51 UTC by rwblokzijl

This PR syncs nvim tree across tabs if `open_on_tab` is set.

Previously: 
 - On tab change this would open nvim-tree
 - When having closed nvim-tree it would still open nvim tree on tab change

Now:

 - when having closed nvim-tree it will sync this on tab change
 - if nvim-tree is closed (using `:quit`) this is also synced across tabs
 - if nvim-tree is the final window in a tab, the tab is closed (if this is the last tab, vim is closed)

2022-10-17 01:26 UTC, alex-courtis commented
> * if nvim-tree is the final window in a tab, the tab is closed (if this is the last tab, vim is closed)

This was present in the past however was removed as it is unavoidably problematic. https://github.com/nvim-tree/nvim-tree.lua/issues/1005#issuecomment-1079824801

You may implement this functionality yourself: https://github.com/nvim-tree/nvim-tree.lua#tips--tricks

2022-10-17 01:29 UTC, alex-courtis commented on lua/nvim-tree.lua
> +  vim.g.nvim_tree_tab_open = 1
We do not use global variables to track nvim-tree state.

Please test via something like:
* iterate windows on tab
* test `utils.is_nvim_tree_buf`

2022-10-17 01:29 UTC, alex-courtis requested changes
I've not tested nor fully reviewed yet.

Please:

- [ ] remove auto close
- [ ] avoid global variable

2022-10-28 20:54 UTC, closed without merging

2022-10-28 21:11 UTC, rwblokzijl commented
Closed by force push i think. See https://github.com/nvim-tree/nvim-tree.lua/pull/1698