fix: reduce signcolumn/foldcolumn from window width
nvim-tree/nvim-tree.lua pull request #1688
Opened 2022-10-26 11:14 UTC by ssiyad

https://github.com/nvim-tree/nvim-tree.lua/issues/1679#issuecomment-1291030546

2022-10-26 13:11 UTC, pleshevskiy commented
I've checked and it works! Thanks!

2022-10-29 03:11 UTC, alex-courtis requested changes
Looking good:

![20221029_135419 441x477](https://user-images.githubusercontent.com/1505378/198796408-b2e8f7bd-1381-429c-b127-863b43245fe7.png)

Please be more defensive:

- [ ] `win_getid` may return 0 which will result in an incorrect result from `getwininfo`
- [ ] `getwininfo` may return an empty list

`textoff` is OK as it is "guaranteed" to be a number for a successful result.

2022-10-31 04:36 UTC, alex-courtis approved these changes
Works beautifully, thank you for the contribution.

2022-10-31 04:36 UTC, alex-courtis commented on lua/nvim-tree/renderer/components/full-name.lua
> +  local win_width = effective_win_width()
nice

2022-10-31 04:38 UTC, merged