feat(diagnostics): only show diagnostic on closed folder
nvim-tree/nvim-tree.lua pull request #1778
Opened 2022-11-27 12:11 UTC by chomosuke

On certain projects there might be deeply nested folders (e.g. java projects). Showing diagnostics on all the parent folders feels very cluttered. It also makes it harder to get a idea of how many files have diagnostics at a glance.

This PR adds the `show_on_open_dirs` which when set to false will only show diagnostics on closed directory.

2022-11-28 01:03 UTC, alex-courtis requested changes
This is valuable functionality, thank you for raising. I will greatly appreciate this functionality.

We currently have feature parity between git and diagnostics via `show_on_dirs` albeit with different defaults.

Let's continue parity: please add `show_on_open_dirs` for git as well.

Update: see #1781 which requested this functionality.

2022-11-28 08:48 UTC, chomosuke commented
Thanks! I'm glad you liked it.

I actually attempted to replicate the functionality for git too before opening this PR but had a little bit of trouble getting it to update without constantly hitting refresh. Hence why I didn't replicate it. 

After some digging I've managed to get it to update without refreshing now. This PR should be ready to review again @alex-courtis. :)

2022-11-28 11:18 UTC, gegoune commented
This is indeed very valuable addition. Thank you!

2022-11-29 00:11 UTC, alex-courtis approved these changes
Tested combinations `enable` `show_on_dirs` `show_on_open_dirs`:
* git
* lsp

2022-11-29 00:12 UTC, merged

2022-11-29 03:49 UTC, alex-courtis commented
It seems that my testing was insufficient: #1786 
I'd be grateful if you looked at that one @chomosuke 

I'm using this functionality for git and diagnostics... my view is so much clearer... many thanks!