Implicit current buf on centralize selection
nvim-tree/nvim-tree.lua pull request #1792
Opened 2022-11-30 23:49 UTC by thedaviddelta

The recent implementation change to center the selected file produces a very odd error on my setup.
If I have `nvim-tree` open (for example, when opening an empty project) and then open a file using any other mean (e.g. Telescope)  a `Invalid buffer id: 1` error pops into my neovim.
Tweaking the code I've discovered the cause: the `centralize_selection` autocmd that runs when closing the tree tries to reads the `bufnr` of Telescope and then schedules the `zz` call, running after some milliseconds when the Telescope buffer is already killed.
By implicitly using the current buffer (by using `0` as a param) instead of explicitly retrieving it solves this problem. It'd probably also work if the retrieving is moved inside the `schedule` function, but haven't tried as I don't think it's better to do so.

2022-12-01 12:41 UTC, gegoune commented
`0` is probably good here but maybe using buffer number from event object will be more robust?

2022-12-01 16:39 UTC, thedaviddelta commented
Changed. I think it's also working correctly this way.

2022-12-01 16:42 UTC, gegoune requested changes

2022-12-01 16:42 UTC, gegoune commented on lua/nvim-tree.lua
> -        local bufnr = vim.api.nvim_get_current_buf()
That can be removed entirely.

2022-12-01 16:42 UTC, gegoune commented on lua/nvim-tree.lua
> +          local bufnr = vim.api.nvim_get_current_buf()
No need to fetch that. It's already available in callback by accepting `event` argument.

2022-12-01 16:42 UTC, gegoune commented on lua/nvim-tree.lua
>            vim.api.nvim_buf_call(bufnr, function()
```suggestion
          vim.api.nvim_buf_call(event.buf, function()
```

2022-12-01 16:42 UTC, gegoune commented on lua/nvim-tree.lua
>        callback = function()
```suggestion
      callback = function(event)
```

2022-12-01 16:43 UTC, gegoune commented
Thanks, that's not exactly what I had in mind. Apologies for not being clear. I have requested changes with more detail.

2022-12-01 16:52 UTC, thedaviddelta commented
![imagen](https://user-images.githubusercontent.com/6679900/205111962-1a567d4e-2d69-4d0f-8e6c-238e03a44326.png)
This produces the same problem, as the event is populated before the schedule starts.
We should just use `0`, or simply query the id **inside** the schedule callback.

2022-12-01 17:11 UTC, gegoune commented
Didn't test it properly then. Schedule it then. Maybe Alex will have better solution.

2022-12-01 17:33 UTC, thedaviddelta commented
Should I revert to the explicit or the implicit implementation?

2022-12-01 17:35 UTC, gegoune commented
If `0` in scheduled context works then it seems like the easiest solution avoiding extra call to api.

2022-12-12 00:59 UTC, alex-courtis commented
Gentle nudge for re-review @gegoune

2022-12-12 12:13 UTC, gegoune approved these changes

2022-12-12 12:14 UTC, merged