Implement turning off y/n prompt for file deletion
nvim-tree/nvim-tree.lua pull request #1887
Opened 2023-01-05 09:18 UTC by amamdemous

I have a suggestion to give users the option to disable the prompt when deleting a file. For example, when working in small folders, there is no particular need to double-check the file you are deleting

2023-01-05 10:57 UTC, gegoune reviewed
We should try to avoid adding new options if at all possible. If the is highly desirable I would like that option name to be changed to something like:

```lua
ui = {
  confirm = {
    node_deletion = true,
  }
}
```

(`node` can actually be called `file`, because everything is a file :)

Would you be willing to add other confirmations as well?

@alex-courtis

2023-01-07 03:21 UTC, alex-courtis commented
> Would you be willing to add other confirmations as well?

Yes. Some of these are annoying, but it would be good to be selective.

How about we add an enable to turn them all off?
```lua
ui = {
  confirm = {
    enable = true,
    node_deletion = true,
    paste = true,
    trash = true,
    create = true,
```

2023-01-07 03:25 UTC, alex-courtis requested changes
Many thanks for taking the initiative on this UX improvement.

Looks like a straightforward refactor.

If you are motivated to make the same change for other operations, and implement `ui.confirm.enable` I would be most grateful.

2023-01-07 03:25 UTC, alex-courtis commented on lua/nvim-tree.lua
> +  file_deletion_confirmation = true,
Please refactor this to `ui.confirm.remove`.

2023-01-07 18:13 UTC, amamdemous commented
Made refactors as suggested

2023-01-08 01:26 UTC, alex-courtis requested changes
Remove works beautifully, trash fails at cf36d35 with:

```
E5108: Error executing lua: ...cker/start/amamdemous/lua/nvim-tree/actions/fs/trash.lua:32: attempt to index field 'trash' (a nil value)
stack traceback:
        ...cker/start/amamdemous/lua/nvim-tree/actions/fs/trash.lua:32: in function 'handle_tree_actions'
        ...cker/start/amamdemous/lua/nvim-tree/actions/dispatch.lua:123: in function 'dispatch'
        ...k/packer/start/amamdemous/lua/nvim-tree/actions/init.lua:273: in function <...k/packer/start/amamdemous/lua/nvim-tree/actions/init.lua:272>
```

2023-01-08 01:26 UTC, alex-courtis commented on doc/nvim-tree-lua.txt
> +      },
Next time please remember to update help as per [CONTRIBUTING](https://github.com/nvim-tree/nvim-tree.lua/blob/master/CONTRIBUTING.md)

Added doc for this section and renamed to match the action.

2023-01-08 06:39 UTC, alex-courtis approved these changes
Works nicely, thank you for your contribution.

2023-01-08 06:43 UTC, merged