fix(#2109): floating help window
nvim-tree/nvim-tree.lua pull request #2120
Opened 2023-04-10 06:55 UTC by alex-courtis

fixes #2109

Work in progress:

- [ ] Styling
- [ ] Remove old help plumbing / drawing
- [ ] Simplify help.lua

2023-04-10 07:10 UTC, gegoune commented on lua/nvim-tree/renderer/help.lua
> +  vim.api.nvim_create_autocmd("WinLeave", {
Shouldn't it set once to true?

2023-04-10 23:52 UTC, alex-courtis commented on lua/nvim-tree/renderer/help.lua
> +  vim.api.nvim_create_autocmd("WinLeave", {
Thank you!

2023-04-11 06:44 UTC, gegoune requested changes

2023-04-11 06:44 UTC, gegoune commented on lua/nvim-tree/help.lua
> +    border = "rounded",
```suggestion
    border = "none",
```

2023-04-11 06:44 UTC, gegoune commented on lua/nvim-tree/help.lua
> +    col = 1,
```suggestion
    col = 0,
```

2023-04-11 06:44 UTC, gegoune commented on lua/nvim-tree/help.lua
> +  local fmt = string.format("%%-%ds %%-%ds", max_lhs, max_desc)
```suggestion
  local fmt = string.format(" %%-%ds %%-%ds", max_lhs, max_desc)
```

2023-04-11 06:44 UTC, gegoune commented on lua/nvim-tree/help.lua
> +  local lines = { "nvim-tree mappings   exit: q" }
```suggestion
```

2023-04-11 06:44 UTC, gegoune commented on lua/nvim-tree/help.lua
> +
```suggestion

  local lines = { ("nvim-tree mappings%sexit: q"):format(string.rep(" ", max_desc + max_lhs - 23)) }
```

2023-04-11 06:44 UTC, gegoune commented on lua/nvim-tree/help.lua
> +  local lines = { "nvim-tree mappings   exit: q" }
Moving down to where we know the width.

2023-04-11 06:44 UTC, gegoune commented on lua/nvim-tree/help.lua
> +
trying to right pad `exit: q`. Still seeing some space to the right but it's most likely just window border/window separator. Keen to see how it looks in your setup.
<img width="408" alt="pad" src="https://user-images.githubusercontent.com/69750637/231077222-5b330e57-5ccf-4540-9de6-bb3be4bd819f.png">

2023-04-11 06:44 UTC, gegoune commented on lua/nvim-tree/help.lua
> +  local fmt = string.format("%%-%ds %%-%ds", max_lhs, max_desc)
Adding padding after removal of border and moving window all the way to the edge.

2023-04-11 06:44 UTC, gegoune commented on lua/nvim-tree/help.lua
> +    border = "rounded",
Opinion: look cleaner without border.

2023-04-11 06:44 UTC, gegoune commented on lua/nvim-tree/help.lua
> +    col = 1,
To cover over sign column.

But we really should check if tree is displayed on left or right side of screen here.

2023-04-12 06:18 UTC, alex-courtis commented
Looking good! Many thanks.

Could you stretch to a single border? I was just updated to neovim 0.9 and they changed the default float background to dark:

![20230412_161738](https://user-images.githubusercontent.com/1505378/231367993-071425b1-ba5f-4346-9092-453f2ffbc7c2.png)

![20230412_161819](https://user-images.githubusercontent.com/1505378/231368113-92358402-b530-4a13-9abe-c234f990320d.png)

2023-04-12 06:19 UTC, alex-courtis commented
Please do just push to the branch in the future... I'm completely OK with cowboy commits.

2023-04-15 04:59 UTC, merged