feat(open-file): Add new node selection action based on :drop command
nvim-tree/nvim-tree.lua pull request #2161
Opened 2023-04-22 09:23 UTC by hinell

https://user-images.githubusercontent.com/8136158/233742234-c4f4bb4b-1927-4ab4-b0cc-779c64a0e1b1.mov

* Demo of the new action allowing to always jumpt to an already-opened window based in built-in command. Every time `<CR>` is hit, the same buffer window of the file is focused.
* Usage docs added

Demo link: `https://user-images.githubusercontent.com/8136158/233742234-c4f4bb4b-1927-4ab4-b0cc-779c64a0e1b1.mov`

### PRs
**PREVIOUS PRs got CLOSED BECAUSE OF FORCE-PUSH, GITHUB IS REALLY NUTS**

2023-04-22 13:21 UTC, hinell commented
@alex-courtis Please merge asap!

2023-04-22 17:01 UTC, gegoune requested changes

2023-04-22 17:01 UTC, gegoune commented on doc/nvim-tree-lua.txt
> +    Usage example: >
Please remove example usage

2023-04-22 18:04 UTC, hinell commented on doc/nvim-tree-lua.txt
> +    Usage example: >
Done.

2023-04-22 20:28 UTC, gegoune requested changes

2023-04-22 20:28 UTC, gegoune commented on lua/nvim-tree/actions/node/open-file.lua
> +
```suggestion
```

2023-04-22 23:40 UTC, gegoune approved these changes
Have updated docs a bit and resolved styling.

Thanks for your contribution.

2023-04-22 23:41 UTC, merged

2023-04-23 10:42 UTC, hinell commented
@gegoune I think we should provide and example somewhere in docs. Otherwise it's a black box for unfamiliar people.

2023-04-23 12:50 UTC, gegoune commented
I am not against examples of course, is just that this one was not well placed. Other api don't provide any examples at all and this is what it should stay as. We can provide some example api usages on top of api help, more generic ones.

2023-04-23 20:30 UTC, hinell commented
@gegoune But where should such docs be placed?

2023-04-23 20:36 UTC, gegoune commented
Actually there is already an example of how to use API functions in `:h nvim-tree-mappings`. Do you think it could be improved?

2023-04-24 03:39 UTC, alex-courtis commented
API would be great!

2023-04-25 18:41 UTC, hinell commented
@

2023-04-25 18:42 UTC, hinell commented
Well I could have made an improvement via this PR, but anyway.

2023-04-25 19:10 UTC, gegoune commented
That wasn't what we wanted to add to docs.

2023-04-29 07:14 UTC, alex-courtis commented
How about we just add a [Recipe](https://github.com/nvim-tree/nvim-tree.lua/wiki/Recipes) ?

The :help is factual and correct.