fix: Watch $GIT_DIR for git changes, if set
nvim-tree/nvim-tree.lua pull request #2263
Opened 2023-06-10 13:53 UTC by zhimsel

## About

While rarely used, it's possible to set the $GIT_DIR environment variable to instruct git to use a directory other than `.git`.

This checks if that environment variable is set; if it is, the plugin will watch that directory. If it's not set, it'll fall back to the default `.git` directory.

## Why?

I use a non-standard `.git` folder in my home directory for my dotfiles (`~/.git_dotfiles`). If I have `$GIT_DIR` set in my env to work on my dotfiles and open up nvim-tree, it'll detect that we're "in a git repo".

Prior to this change, it would produce an error that it can't watch the `.git` directory (since it doesn't exist). With this change, it produces no error and correctly watches the `$GIT_DIR` directory.

## Testing

I tested this in my environment by opening up nvim and nvim-tree in various scenarios, ensuring that no errors are produced and git changes are correctly detected (or correctly absent):

- [x] Not in a git repo and `$GIT_DIR` unset
- [x] In a git repo with a `.git` directory and `$GIT_DIR` unset
- [x] In a git repo with a non-standard git-dir and `$GIT_DIR` unset
- [x] In a git repo with a non-standard git-dir and `$GIT_DIR` set to that directory

2023-06-11 02:54 UTC, alex-courtis commented
We added such functionality in #2012 however that resulted in a regression and was backed out.

There's a PR open now to reintroduce that functionality #2194

This does seem a lot simpler: just using `$GIT_DIR` when set. In the previous PR we checked `git -C /path/to/repo rev-parse --absolute-git-dir`

I'm not sure how this works in test case 3; I'll test it out.

2023-06-12 05:41 UTC, alex-courtis requested changes
Unfortunately there are also extra regular file system watchers created for the custom git directory.

Example with `GIT_DIR=/home/alex/2263/nvt/.cgd`

You can see two watchers for `.cgd`. The first one is the desired one, with the filtered set of files.

```
[2023-06-12 15:35:52] [watcher] Watcher:new '/home/alex/2263/nvt' nil
[2023-06-12 15:35:52] [watcher] Event:new '/home/alex/2263/nvt'
[2023-06-12 15:35:52] [watcher] Event:start '/home/alex/2263/nvt'
[2023-06-12 15:35:52] [git] { "git", "-C", "/home/alex/2263/nvt", "rev-parse", "--show-toplevel" }
/home/alex/2263/nvt
[2023-06-12 15:35:52] [git] { "git", "-C", "/home/alex/2263/nvt", "config", "status.showUntrackedFiles" }
[2023-06-12 15:35:52] [git] running job with timeout 400ms
[2023-06-12 15:35:52] [git] git --no-optional-locks status --porcelain=v1 -z --ignored=matching -u
 M .editorconfig
?? .cgd/HEAD
?? .cgd/config
?? .cgd/description
?? .cgd/hooks/applypatch-msg.sample
?? .cgd/hooks/commit-msg.sample
?? .cgd/hooks/fsmonitor-watchman.sample
?? .cgd/hooks/post-update.sample
?? .cgd/hooks/pre-applypatch.sample
?? .cgd/hooks/pre-commit.sample
?? .cgd/hooks/pre-merge-commit.sample
?? .cgd/hooks/pre-push.sample
?? .cgd/hooks/pre-rebase.sample
?? .cgd/hooks/pre-receive.sample
?? .cgd/hooks/prepare-commit-msg.sample
?? .cgd/hooks/push-to-checkout.sample
?? .cgd/hooks/sendemail-validate.sample
?? .cgd/hooks/update.sample
?? .cgd/index
?? .cgd/info/exclude
?? .cgd/logs/HEAD
?? .cgd/logs/refs/heads/master
?? .cgd/logs/refs/remotes/origin/HEAD
?? .cgd/objects/pack/pack-86c3790f9768d4f5a4503823707e87ab8adfaea4.idx
?? .cgd/objects/pack/pack-86c3790f9768d4f5a4503823707e87ab8adfaea4.pack
?? .cgd/objects/pack/pack-86c3790f9768d4f5a4503823707e87ab8adfaea4.rev
?? .cgd/packed-refs
?? .cgd/refs/heads/master
?? .cgd/refs/remotes/origin/HEAD
!! .cgd/refs/tags/
[2023-06-12 15:35:52] [git] done
[2023-06-12 15:35:52] [git] job success    /home/alex/2263/nvt nil
[2023-06-12 15:35:52] [watcher] git start
[2023-06-12 15:35:52] [watcher] Watcher:new '/home/alex/2263/nvt/.cgd' { "FETCH_HEAD", "HEAD", "HEAD.lock", "config", "index" }
[2023-06-12 15:35:52] [watcher] Event:new '/home/alex/2263/nvt/.cgd'
[2023-06-12 15:35:52] [watcher] Event:start '/home/alex/2263/nvt/.cgd'
[2023-06-12 15:35:52] [watcher] Watcher:new '/home/alex/2263/nvt/.cgd' nil
[2023-06-12 15:35:52] [watcher] Watcher:new '/home/alex/2263/nvt/.github' nil
[2023-06-12 15:35:52] [watcher] Event:new '/home/alex/2263/nvt/.github'
[2023-06-12 15:35:52] [watcher] Event:start '/home/alex/2263/nvt/.github'
[2023-06-12 15:35:52] [watcher] Watcher:new '/home/alex/2263/nvt/.hooks' nil
[2023-06-12 15:35:52] [watcher] Event:new '/home/alex/2263/nvt/.hooks'
[2023-06-12 15:35:52] [watcher] Event:start '/home/alex/2263/nvt/.hooks'
[2023-06-12 15:35:52] [watcher] Watcher:new '/home/alex/2263/nvt/doc' nil
[2023-06-12 15:35:52] [watcher] Event:new '/home/alex/2263/nvt/doc'
[2023-06-12 15:35:52] [watcher] Event:start '/home/alex/2263/nvt/doc'
```

Maybe take a look at #2194 and see if you can pull something from there.

2023-06-12 05:41 UTC, alex-courtis commented on lua/nvim-tree/git/init.lua
> +    local git_dir = vim.env.GIT_DIR or utils.path_join { project_root, ".git" }
This works.

2023-07-06 18:10 UTC, zhimsel commented
^ rebase on latest `master`.

2023-07-06 18:13 UTC, zhimsel commented
> Unfortunately there are also extra regular file system watchers created for the custom git directory.
> You can see two watchers for `.cgd`. The first one is the desired one, with the filtered set of files.

@alex-courtis you're referring to these two lines?

```
[2023-06-12 15:35:52] [watcher] Watcher:new '/home/alex/2263/nvt/.cgd' { "FETCH_HEAD", "HEAD", "HEAD.lock", "config", "index" }
[2023-06-12 15:35:52] [watcher] Watcher:new '/home/alex/2263/nvt/.cgd' nil
```

I'm guessing that second one is created just by the fact that it's a file in the current directory? I suppose we could have it ignore any files that are the value of `$GIT_DIR` if it's set...

2023-07-06 19:06 UTC, zhimsel commented
@alex-courtis I modified the "is this a git dir?" function for the file ignores to account for `$GIT_DIR` being set, as well as accounting for possibly non-absolute `$GIT_DIR` values.

I tested it on my machine with various scenarios of `$GIT_DIR` being set and unset, being relative and absolute, and being in and out of git repos. Seems to work as expected with no duplicate watchers.

2023-07-10 03:10 UTC, alex-courtis commented
Thanks for the updates @zhimsel 

I'll get to review and test this weekend.

2023-07-15 03:57 UTC, alex-courtis commented
I don't have permission to rebase; I'll leave that to you. There look to be no conflicts.

2023-07-15 04:39 UTC, alex-courtis approved these changes
This works for the following case:
```sh
:; export GIT_DIR=~/2263/cgd
:; export GIT_WORK_TREE=~/2263/nvt
:; cd ~/2263
:; mkdir nvt
:; cd nvt
:; echo bar > foo
:; git add foo
:; git commit -a -m "initial commit"

:; git rev-parse --show-toplevel
/home/alex/2263/nvt

:; git rev-parse --git-dir
/home/alex/2263/cgd
```

`$GIT_WORK_TREE` set or unset
`$GIT_DIR` set

My git knowledge is insufficient to test cloning an existing repo with non-standard `--git-dir` however it should behave in a similar manner.

- [x] Please rebase.

2023-07-15 13:58 UTC, zhimsel commented
> Please rebase.

Done! Sidenote: I renamed the original commit to use `feat:` to match your reclassification of this PR.

> My git knowledge is insufficient to test cloning an existing repo with non-standard --git-dir however it should behave in a similar manner.

It's as simple as just setting `$GIT_DIR` in your shell and cloning! Git will use that directory instead of `.git`. The `--git-dir` command argument should work as well, it just has to be set for _every_ command against your cloned repo, including anything like shell prompts and vim plugins. Y

2023-07-15 13:59 UTC, zhimsel commented
Whoops, ignore that closure. I tabbed one too many times before hitting enter 😞

2023-07-16 02:44 UTC, alex-courtis approved these changes
Many thanks for pushing this difficult one through.

2023-07-16 02:44 UTC, merged

2023-07-16 16:24 UTC, zhimsel commented
No problem! Thanks for reviewing and merging.