feat(#135 float-preview): float preview
nvim-tree/nvim-tree.lua pull request #2290
Opened 2023-06-22 22:09 UTC by JMarkin

Hello, I implemented this feature.

I think this feature would be used like `Recipe` like this:
```lua 
local function on_attach(bufnr)
    local api = require("nvim-tree.api")
    local FloatPreview = require("nvim-tree.float-preview")

    local prev, float_close_wrap = FloatPreview:new()
    prev:attach(bufnr)
    --- There are keymaps must to wrap for correct work
    -- ...
    vim.keymap.set("n", "<C-t>", float_close_wrap(api.node.open.tab), opts("Open: New Tab"))
    vim.keymap.set("n", "<C-v>", float_close_wrap(api.node.open.vertical), opts("Open: Vertical Split"))
    vim.keymap.set("n", "<C-s>", float_close_wrap(api.node.open.horizontal), opts("Open: Horizontal Split"))
    vim.keymap.set("n", "<CR>", float_close_wrap(api.node.open.edit), opts("Open"))
    vim.keymap.set("n", "<Tab>", float_close_wrap(api.node.open.preview), opts("Open"))
    vim.keymap.set("n", "o", float_close_wrap(api.node.open.edit), opts("Open"))
    vim.keymap.set("n", "O", float_close_wrap(api.node.open.no_window_picker), opts("Open: No Window Picker"))
    vim.keymap.set("n", "q", float_close_wrap(api.tree.close), opts("Close"))
    vim.keymap.set("n", "a", float_close_wrap(api.fs.create), opts("Create"))
    vim.keymap.set("n", "d", float_close_wrap(api.fs.remove), opts("Delete"))
    vim.keymap.set("n", "r", float_close_wrap(api.fs.rename), opts("Rename"))
 end
```

Currently it has 2 surprise for me
1. If lsp enabled with auto_attach=true, after open any buffer and lsp attached, preview buffer didn't unload(or load twice, I don't understand)
2. If style == 'minimal', after open file it would be open in minimal mode(would be disable many options)

2023-06-25 03:31 UTC, alex-courtis commented
This looks incredible! The preview is working with this PR as well as with `"JMarkin/nvim-tree.lua-float-preview"`.

I'm not sure if I'm doing it right but I'm seeing the contents appear in both the floating window as well as the "regular" window when I tab preview:

![20230625_133043](https://github.com/nvim-tree/nvim-tree.lua/assets/1505378/1d519338-efc4-4b25-bd62-cf4a544f23bb)

2023-06-25 03:41 UTC, alex-courtis commented
> May be to need only plugin and Recipe ? What do you think?

Rather than a recipe, we should make this an Official [wiki: Extension Plugin](https://github.com/nvim-tree/nvim-tree.lua/wiki/Extension-Plugins). An entry in [wiki: Installation](https://github.com/nvim-tree/nvim-tree.lua/wiki/Installation) should also be added.

Ideas for improvements before we publish:
* Add a `setup` as per nvim-tree's setup, with an `open_win_config` to match nvim-tree's `view.float.open_win_config`. Users love to modify that ;)
* Please use `api.tree.get_node_under_cursor` rather than lib

2023-06-25 03:44 UTC, alex-courtis commented
>    If lsp enabled with auto_attach=true, after open any buffer and lsp attached, preview buffer didn't unload(or load twice, I don't understand)

Could you add an `LspAttach` event handler to "fix" this behaviour?

>    If style == 'minimal', after open file it would be open in minimal mode(would be disable many options)

If you had a setup user configuration, you could disable / remove that with a warning that minimal is unavailable.

2023-06-25 03:47 UTC, alex-courtis requested changes

2023-06-25 03:47 UTC, alex-courtis commented on lua/nvim-tree/float-preview.lua
> +local get_node = require("nvim-tree.lib").get_node_at_cursor
Please use api.tree.get_node_under_cursor rather than lib

2023-06-26 21:54 UTC, JMarkin commented
> > May be to need only plugin and Recipe ? What do you think?
> 
> Rather than a recipe, we should make this an Official [wiki: Extension Plugin](https://github.com/nvim-tree/nvim-tree.lua/wiki/Extension-Plugins). An entry in [wiki: Installation](https://github.com/nvim-tree/nvim-tree.lua/wiki/Installation) should also be added.
> 
> Ideas for improvements before we publish:
> 
>     * Add a `setup` as per nvim-tree's setup, with an `open_win_config` to match nvim-tree's `view.float.open_win_config`. Users love to modify that ;)
> 
>     * Please use `api.tree.get_node_under_cursor` rather than lib
> 
>     * Copy some nvim-tree configuration files into your repo:
>       
>       * `.editorconfig`
>       * `.luacheckrc`
>       * `.luarc.json`
>       * `.stylua.toml`

@alex-courtis I fixed all your comments in [repo](https://github.com/JMarkin/nvim-tree.lua-float-preview). Should this PR to closed? Or you think integrate this to nvim-tree.lua more correct?

2023-06-27 01:23 UTC, alex-courtis commented
> I fixed all your comments in [repo](https://github.com/JMarkin/nvim-tree.lua-float-preview).

This looks good. The user has multiple ways to configure i.e.
```
require("nvim-tree").setup({
  on_attach = my_on_attach,
})
require("float-preview").setup({
  scroll_lines = 123,
})

-- or

local prev, float_close_wrap = FloatPreview:new({
  scroll_lines = 123,
})
```

> Or you think integrate this to nvim-tree.lua more correct?

The level of integration is great: no nvim-tree configuration is required to start and use `"JMarkin/nvim-tree.lua-float-preview"`, other than the actual `on_attach` mappings.

2023-06-27 01:26 UTC, alex-courtis commented
Does the user have to `new` float preview inside their on_attach? Could they just create it once e.g.

```lua
local float_preview, float_preview_wrap = require("float-preview"):new({ ... })

function M.on_attach(bufnr)
---
  float_preview:attach(bufnr)
  vim.keymap.set("n", "<C-t>", float_preview_wrap(api.node.open.tab), opts("Open: New Tab"))
---
end
```

2023-06-27 01:47 UTC, alex-courtis commented
Unfortunately I still don't understand how the plugin works. I am doing it wrong.

* How do I close the preview window? It only closed when I `q` nvim-tree
* The preview window always show the currently opened buffer. How do I keep it on the previewed buffer? I'd like to have a different preview window than the buffer I am editing.

See [![asciicast](https://asciinema.org/a/593422.svg)](https://asciinema.org/a/593422)

2023-06-27 02:32 UTC, alex-courtis commented
I've added a draft help file https://github.com/JMarkin/nvim-tree.lua-float-preview/pull/2

It needs some work.

2023-07-08 06:40 UTC, alex-courtis commented
The external plugin is looking good and can be added to the wiki when it's ready.

2023-07-08 06:40 UTC, closed without merging