fix(#2369): Better "y/N" prompts
nvim-tree/nvim-tree.lua pull request #2377
Opened 2023-08-15 17:05 UTC by mohamedarish

This is the solution for issue #2370.

Packer uses a bool flag comparing to check whether the given input is "y".

I've made it so that the default behaviour of the prompt is set to N for no (don't delete).

The default is set to R(ename) for name conflicts when copy-pasting.

Accidentally clicking enter/return after pressing d/bd should be made less common with this default behaviour.

the default behaviour is shown as a capital letter.

2023-08-15 18:25 UTC, mohamedarish commented
I've thought about it and the "no" condition is unnecessary as everything that is not "y" is a no condition. I'm closing this PR and would be reopening this after I've fixed this issue.

2023-08-16 00:06 UTC, alex-courtis commented
Thanks for taking the time. This one is indeed more difficult than it appears.

2023-08-16 15:34 UTC, mohamedarish commented
I've removed all "No" conditions as they are not needed as everything that is not a "y" or "yes" entered is a no condition. And would delete/replace the files

2023-08-20 05:00 UTC, alex-courtis requested changes
Many thanks for your contribution. This greatly enhances UX.

- [x] maybe address default `r`
- [x] Please update `lib.prompt` to convert the callback's item_short to lowercase. Users may start using uppercase to match the prompt.

2023-08-20 05:13 UTC, mohamedarish commented on lua/nvim-tree/actions/fs/copy-paste.lua
> +      lib.prompt(prompt_input, prompt_select, { "r", "y" }, { "Rename", "Yes" }, function(item_short)
anything that does not start with y or n shall become r in that case?
This feels wrong and having don't copy be the default case feels better

2023-08-20 05:14 UTC, mohamedarish commented on lua/nvim-tree/actions/fs/copy-paste.lua
> +      lib.prompt(prompt_input, prompt_select, { "r", "y" }, { "Rename", "Yes" }, function(item_short)
I have already started working on making it lowercase

2023-08-20 05:36 UTC, alex-courtis commented on lua/nvim-tree/actions/fs/copy-paste.lua
> +      lib.prompt(prompt_input, prompt_select, { "r", "y" }, { "Rename", "Yes" }, function(item_short)
> anything that does not start with y or n shall become r in that case?
> This feels wrong and having don't copy be the default case feels better

Yes please. Default `n` is consistent and arguably better behaviour. All prompts default to no.

It's a somewhat breaking change however it is quite reasonable.

2023-08-20 06:16 UTC, mohamedarish commented
I've noticed that my change makes the prompt ui from [dressing.nvim](https://github.com/stevearc/dressing.nvim) or [telescope-ui-select.nvim
](https://github.com/nvim-telescope/telescope-ui-select.nvim) and have updated the items_long to fix this and also fixed to change all item_short to be lowercase.

2023-08-20 06:24 UTC, mohamedarish commented on lua/nvim-tree/actions/fs/copy-paste.lua
> +      lib.prompt(prompt_input, prompt_select, { "r", "y" }, { "Rename", "Yes" }, function(item_short)
Currently "r" is auto filled when a name conflict on copy occurs and I feel that is a better behaviour than defaulting to don't copy in that case.
The user needs to remove the r or update the autofilled character as it provides a second chance to cancel by cancelling the rename prompt

2023-08-20 06:54 UTC, alex-courtis commented
> I've noticed that my change makes the prompt ui from [dressing.nvim](https://github.com/stevearc/dressing.nvim) or [telescope-ui-select.nvim ](https://github.com/nvim-telescope/telescope-ui-select.nvim) not have proper select prompts (Default(No) appears as is and does not fit into the prompt ui) and have updated the items_long to fix this and also fixed to change all item_short to be lowercase.

Thank you for testing.

2023-08-20 07:03 UTC, alex-courtis requested changes
Please:

- [x] resolve exception
- [x] remove auto-fill r

2023-08-20 07:03 UTC, alex-courtis commented on lua/nvim-tree/actions/fs/copy-paste.lua
> +      lib.prompt(prompt_input, prompt_select, { "r", "y" }, { "Rename", "Yes" }, function(item_short)
> Currently "r" is auto filled when a name conflict on copy occurs and I feel that is a better behaviour than defaulting to don't copy in that case.

I'm happy with `r` as the default, however auto-filling is not consistent with other prompts. We can remove the auto-fill and rename can still be the default.

2023-08-20 07:05 UTC, mohamedarish commented on lua/nvim-tree/actions/fs/copy-paste.lua
> +      lib.prompt(prompt_input, prompt_select, { "r", "y", "n" }, { "Rename", "Yes", "No" }, function(item_short)
I have already resolved the exception, Will remove the auto-fill r

2023-08-20 07:27 UTC, mohamedarish commented on lua/nvim-tree/actions/fs/copy-paste.lua
> +      lib.prompt(prompt_input, prompt_select, { "r", "y", "n" }, { "Rename", "Yes", "No" }, function(item_short)
I have fixed the exception and added another condition in the elseif block for rename for rename to be "r"/"R" or ""

2023-08-20 07:32 UTC, alex-courtis approved these changes
All cases tested OK.

Many thanks for your contribution.

2023-08-20 07:34 UTC, merged