fix: file creation in empty folder without root_folder_label
nvim-tree/nvim-tree.lua pull request #2514
Opened 2023-11-06 09:17 UTC by geril2207

Fixes: #2512

2023-11-06 23:19 UTC, alex-courtis requested changes
Thank you for your contribution:

Tested OK except there is an issue:

`root_folder_label =  ":~:s?$?/..?"`
- [ ] add multiple files 
- [ ] add multiple folders
- [ ] add mix

`root_folder_label = false`
- [ ] add multiple files 
- [ ] add multiple folders
- [ ] add mix

issue:
<CR> on empty root node navigates up a directory

2023-11-06 23:21 UTC, alex-courtis commented on lua/nvim-tree/lib.lua
I'm not sure we can make this fix here: `get_node_at_cursor` is used in a great many places and there are assumptions that it will return nil if the tree is empty and root folder hidden.

Could we make this change specifically in the add function?

2023-11-06 23:46 UTC, geril2207 commented
@alex-courtis Could you please describe `on empty root node navigates up a directory`. I guess i have no trouble with it.

2023-11-06 23:49 UTC, geril2207 commented on lua/nvim-tree/lib.lua
The main problem in this function which used for all api functions:
```
local function wrap_node(f)
  return function(node, ...)
    node = node or require("nvim-tree.lib").get_node_at_cursor()
    if node then
      f(node, ...)
    end
  end
end
```
`get_node_at_cursor` returns `nil` and stops execution. in `add` function handle already exists
```
function M.fn(node)
  node = node and lib.get_last_group_node(node)
  if not node or node.name == ".." then
    node = {
      absolute_path = core.get_cwd(),
      nodes = core.get_explorer().nodes,
      open = true,
    }
  end
``` 
There are few options we can do:
1. Make another wrapper without `if node then `;
2. Add second param to `wrap_node` which would be true by default, kind of `skip_if_nil`, we can add to ther api calls if need to skip or not and it would be look like this:
```
local function wrap_node(f, skip_if_nil_node)
  return function(node, ...)
    node = node or require("nvim-tree.lib").get_node_at_cursor()
    if skip_if_nil_node or node then
      f(node, ...)
    end
  end
end
```

2023-11-07 00:22 UTC, geril2207 commented
@alex-courtis So what do you think about current solution?

2023-11-07 01:51 UTC, alex-courtis requested changes
Pragmatic and safe.

API is a bit of a mess and adding boolean arguments isn't the best for readability.

Could you please add a specific method, maybe `wrap_node_or_nil`

2023-11-07 01:51 UTC, alex-courtis commented on lua/nvim-tree/api.lua
> +---@param fn function function to invoke
Thank you.

2023-11-07 21:59 UTC, alex-courtis approved these changes
Fantastic work, thank you!

2023-11-07 22:01 UTC, merged