fix(#2468): always apply filters to subdirectories
nvim-tree/nvim-tree.lua pull request #2537
Opened 2023-11-18 22:31 UTC by Akmadan23

I might have found a fix for #2468, and if so it's a really simple one. From my tests it seems to apply correctly all filters to all subdirs, not sure about the resource leaks but they should go together as well.

2023-11-19 04:13 UTC, alex-courtis requested changes
Good catch!

This looks correct and will now correctly handle closed refreshes. However... we're now watching `.git/*` directories. We'll need to somehow apply the exclusions that are present elsewhere.

Testing branch vs master:

```diff
: ; diff --unified=1000 <(sed -e 's/.*watcher] //g' /tmp/ma.log) <(sed -e 's/.*watcher] //g' /tmp/br.log)
--- /proc/self/fd/11	2023-11-19 15:07:11.978193749 +1100
+++ /proc/self/fd/12	2023-11-19 15:07:11.974860405 +1100
@@ -1,33 +1,48 @@
 Watcher:new '/home/alex/src/nvim-tree/r/2468' nil
 Event:new '/home/alex/src/nvim-tree/r/2468'
 Event:start '/home/alex/src/nvim-tree/r/2468'
 git start
 Watcher:new '/home/alex/src/nvim-tree/r/2468/.git' { "FETCH_HEAD", "HEAD", "HEAD.lock", "config", "index" }
 Event:new '/home/alex/src/nvim-tree/r/2468/.git'
 Event:start '/home/alex/src/nvim-tree/r/2468/.git'
 Watcher:new '/home/alex/src/nvim-tree/r/2468/n' nil
 Event:new '/home/alex/src/nvim-tree/r/2468/n'
 Event:start '/home/alex/src/nvim-tree/r/2468/n'
 Watcher:new '/home/alex/src/nvim-tree/r/2468/n/1' nil
 Event:new '/home/alex/src/nvim-tree/r/2468/n/1'
 Event:start '/home/alex/src/nvim-tree/r/2468/n/1'
 Watcher:new '/home/alex/src/nvim-tree/r/2468/n/2' nil
 Event:new '/home/alex/src/nvim-tree/r/2468/n/2'
 Event:start '/home/alex/src/nvim-tree/r/2468/n/2'
 Watcher:new '/home/alex/src/nvim-tree/r/2468/n/3' nil
 Event:new '/home/alex/src/nvim-tree/r/2468/n/3'
 Event:start '/home/alex/src/nvim-tree/r/2468/n/3'
 Watcher:new '/home/alex/src/nvim-tree/r/2468/i' nil
 Event:new '/home/alex/src/nvim-tree/r/2468/i'
 Event:start '/home/alex/src/nvim-tree/r/2468/i'
+Watcher:new '/home/alex/src/nvim-tree/r/2468/.git/branches' nil
+Event:new '/home/alex/src/nvim-tree/r/2468/.git/branches'
+Event:start '/home/alex/src/nvim-tree/r/2468/.git/branches'
+Watcher:new '/home/alex/src/nvim-tree/r/2468/.git/hooks' nil
+Event:new '/home/alex/src/nvim-tree/r/2468/.git/hooks'
+Event:start '/home/alex/src/nvim-tree/r/2468/.git/hooks'
+Watcher:new '/home/alex/src/nvim-tree/r/2468/.git/info' nil
+Event:new '/home/alex/src/nvim-tree/r/2468/.git/info'
+Event:start '/home/alex/src/nvim-tree/r/2468/.git/info'
+Watcher:new '/home/alex/src/nvim-tree/r/2468/.git/objects' nil
+Event:new '/home/alex/src/nvim-tree/r/2468/.git/objects'
+Event:start '/home/alex/src/nvim-tree/r/2468/.git/objects'
+Watcher:new '/home/alex/src/nvim-tree/r/2468/.git/refs' nil
+Event:new '/home/alex/src/nvim-tree/r/2468/.git/refs'
+Event:start '/home/alex/src/nvim-tree/r/2468/.git/refs'
 Watcher:new '/home/alex/src/nvim-tree/r/2468/i/1' nil
 Event:new '/home/alex/src/nvim-tree/r/2468/i/1'
 Event:start '/home/alex/src/nvim-tree/r/2468/i/1'
 Watcher:new '/home/alex/src/nvim-tree/r/2468/i/2' nil
 Event:new '/home/alex/src/nvim-tree/r/2468/i/2'
 Event:start '/home/alex/src/nvim-tree/r/2468/i/2'
 Watcher:new '/home/alex/src/nvim-tree/r/2468/i/3' nil
 Event:new '/home/alex/src/nvim-tree/r/2468/i/3'
 Event:start '/home/alex/src/nvim-tree/r/2468/i/3'
 Watcher:destroy '/home/alex/src/nvim-tree/r/2468/i'
 Event:destroy '/home/alex/src/nvim-tree/r/2468/i'
```

2023-11-19 14:48 UTC, Akmadan23 commented
Not sure what the correct behavior should be, I did some tests and the watchers are triggered for `.git` subdirs only if `.git` is visible, which makes sense... What are the exclusions that might be present elsewhere?

2023-11-20 00:32 UTC, alex-courtis commented
> Not sure what the correct behavior should be, I did some tests and the watchers are triggered for `.git` subdirs only if `.git` is visible, which makes sense... What are the exclusions that might be present elsewhere?

I see. I think I had some incorrect assumptions around existing behaviour.

The files that trigger a full refresh are the curated list: https://github.com/nvim-tree/nvim-tree.lua/blob/28c3980b25e50e9ede39df55427151cb11be46f9/lua/nvim-tree/git/init.lua#L22 to avoid unwanted noise.

These directories are treated like any other and thus shouldn't result in any performance issues.

I'm happy if you are.

2023-11-20 00:32 UTC, alex-courtis approved these changes

2023-11-20 10:43 UTC, merged