feat: add `api.tree.inspect_node_under_cursor`
nvim-tree/nvim-tree.lua pull request #2541
Opened 2023-11-19 14:54 UTC by Akmadan23

I often use this little function, exposing it in the api might be useful to someone.

2023-11-20 00:43 UTC, alex-courtis requested changes
I like the idea - it will be most useful to have something that I always end up adding log lines for.

I am a bit hesitant:
1. Inspecting nodes is _massive_ as it goes up and down the tree.
2. I don't want to encourage users to look into nodes. They are private and definitely shouldn't be mutated.

How about:
* Change this to log raw instead of print
* Accept an `options` parameter to pass directly to vim.inspect

2023-11-20 00:44 UTC, alex-courtis commented
RE 2. I wish we'd never let the nodes escape into public API. I'd like to provide a sanitised copy of nodes like `sort.sorter` however that's going to be difficult...

2023-11-20 11:12 UTC, Akmadan23 commented
I understand your concerns

> Change this to log raw instead of print

This can be a good idea, but I don't know if it should go in the API, I'd rather put it in the `log` module...

2023-11-20 23:53 UTC, alex-courtis commented
> This can be a good idea, but I don't know if it should go in the API, I'd rather put it in the `log` module...

Ah, that would work nicely. I imagine myself doing something like this in an event or mapping:
```lua
local log = require("nvim-tree.log")
log.node("dev", node, "Event.NodeRenamed %s", data.new_name)
```

I'm happy with your best judgement. This will be useful.

2023-11-20 23:53 UTC, alex-courtis approved these changes
pre-emptive approval

2023-11-23 21:38 UTC, Akmadan23 commented on lua/nvim-tree/log.lua
> +function M.set_inspect_opts(opts)
Since the inspect options are rarely changed, I chose to add this little function to set them instead of another parameter to the `node` function.

2023-11-25 04:06 UTC, alex-courtis approved these changes
Works beautifully, many thanks.

Do you want me to just merge after approval or do you want to do it?

2023-11-25 04:06 UTC, alex-courtis commented on lua/nvim-tree/log.lua
> +    node = node or require("nvim-tree.lib").get_node_at_cursor()
That is very handy...

2023-11-25 20:45 UTC, Akmadan23 commented
> Do you want me to just merge after approval or do you want to do it?

Oh, it's really no different to me, just merge whenever you feel like the PR is ready

2023-11-25 20:45 UTC, merged

2023-11-25 22:37 UTC, alex-courtis commented
> > Do you want me to just merge after approval or do you want to do it?
> 
> Oh, it's really no different to me, just merge whenever you feel like the PR is ready

I am also happy either way.