WIP: feat(#2826): add node API methods for deleting/wiping buffers
nvim-tree/nvim-tree.lua pull request #3040
Opened 2024-12-30 20:45 UTC by GCrispino

This PR adds two API methods for respectively deleting and wiping the buffer for the current file under the tree cursor:
- `Api.node.buffer.delete`; and
- `Api.node.buffer.wipe`.

They both use the same underlying function defined in the new file added at `lua/actions/node/utils.lua`.
This function checks if there's an opened and loaded buffer for the file under the tree cursor.
If there isn't, it notifies an error message.

Otherwise, it deletes/wipes the buffer if it's not modified (unless `opts.force` is `true`)

I'm setting this as WIP because I haven't run the make commands yet.

2025-01-13 03:41 UTC, alex-courtis requested changes
This works nicely, I look forward to using it.

- [x] Revert `ApiTreeToggleOpts` change
- [x] Change warning level of no-loaded-buffer
- [ ] Remove unused options `delete_buffer` and `wipe_buffer`
- [ ] Refactor action methods, message to follow
- [ ] Add help at  6.3 API NODE                                             *nvim-tree-api.node*

2025-01-13 03:41 UTC, alex-courtis commented on lua/nvim-tree/api.lua
> +---@class ApiTreeToggleOptsApiTreeTo
What's the reason for this change? `lua/nvim-tree/actions/tree/toggle.lua` is still using this class...

2025-01-13 03:41 UTC, alex-courtis commented on lua/nvim-tree/api.lua
> +---@field force boolean|nil default false
Thank you.

2025-01-13 03:41 UTC, alex-courtis commented on lua/nvim-tree.lua
> +    wipe_buffer = {},
Are these options used?

2025-01-13 03:41 UTC, alex-courtis commented on lua/nvim-tree/actions/node/utils.lua
Tested permutations and combination with `:ls!` reporting as expected.

```lua
  vim.keymap.set("n", "BW", function()
    api.node.buffer.wipe(api.tree.get_node_under_cursor(), { force = false })
  end, opts("Wipe"))

  vim.keymap.set("n", "BD", function()
    api.node.buffer.wipe(api.tree.get_node_under_cursor(), { force = true })
  end, opts("Delete"))
```

2025-01-13 03:41 UTC, alex-courtis commented on lua/nvim-tree/actions/node/utils.lua
> +    notify.error("No loaded buffer coincides with " .. notify_node)
Can we please change this to INFO? Users may wish to ignore this message.

2025-01-13 03:50 UTC, alex-courtis commented
I like the modularity, it's really easy to read.

Having 3 new files is not necessary, delete and wipe can be handled in one place:
Create a single file `buffer.lua`: containing the utils function and `fn(` methods renamed to `wipe` and `delete`.
We don't really need the `fn()` pattern any more.

These actions do act on a node, and belong in `actions/node`. Rather than the `absolute_path` being passed in, the node itself should be passed in:
1. Prevents error when the user passes a node without that field.
2. Allows testing of the node's type: we don't want to try and delete directories or the tree node. That can silently exit.

2025-01-15 01:36 UTC, GCrispino commented on lua/nvim-tree/api.lua
> +---@class ApiTreeToggleOptsApiTreeTo
No idea 😅 , this was probably done accidentally. Just reverted it 👍🏼

2025-01-15 01:38 UTC, GCrispino commented on lua/nvim-tree.lua
> +    wipe_buffer = {},
No, I was unsure if it was a convention to have these even if there are no underlying options, so I added these in even though they are empty.

I can remove them 👍🏼

2025-01-15 01:38 UTC, GCrispino commented on lua/nvim-tree/actions/node/utils.lua
Great! Thank you 👍🏼

2025-01-15 01:41 UTC, GCrispino commented on lua/nvim-tree/actions/node/utils.lua
> +    notify.error("No loaded buffer coincides with " .. notify_node)
Yeah, sure! Should I also change the error statement at line 37 (the one that says `"Buffer for file " .. notify_node .. " is modified"`), or just this one?

2025-01-15 01:46 UTC, GCrispino commented
> I like the modularity, it's really easy to read.
> 
> Having 3 new files is not necessary, delete and wipe can be handled in one place: Create a single file `buffer.lua`: containing the utils function and `fn(` methods renamed to `wipe` and `delete`. We don't really need the `fn()` pattern any more.
> 
> These actions do act on a node, and belong in `actions/node`. Rather than the `absolute_path` being passed in, the node itself should be passed in:
> 
> 1. Prevents error when the user passes a node without that field.
> 2. Allows testing of the node's type as a `FileNode`. We don't want to try and delete directories or the tree node itself. That can silently exit.

Ok, when I get some free time I'll work on these changes. Thanks for the review :)

2025-01-17 23:30 UTC, alex-courtis commented on lua/nvim-tree/actions/node/utils.lua
> +    notify.error("No loaded buffer coincides with " .. notify_node)
I think just this one. Deleting a modified buffer truly is an error.

2025-01-18 02:55 UTC, GCrispino commented on lua/nvim-tree/actions/node/utils.lua
> +    notify.error("No loaded buffer coincides with " .. notify_node)
Ok, done!

2025-01-18 02:57 UTC, GCrispino commented
@alex-courtis I've pushed some commits, and I believe I have addressed all of your issues :)

Kindly check when you can 🙏🏼 , thanks!

2025-01-23 22:32 UTC, alex-courtis commented
Looks like we have some newly deprecated nvim methods : https://github.com/nvim-tree/nvim-tree.lua/actions/runs/12939265657/job/36091177064?pr=3040

I'll resolve them on master and merge.

2025-01-23 22:42 UTC, alex-courtis approved these changes
In the interests of speed, I pushed fixes for the review comments.

Please let me know if you'd prefer me not to push.

2025-01-23 22:42 UTC, alex-courtis commented on lua/nvim-tree/actions/node/utils.lua
Looks like this file can go - everything is in buffer.lua

2025-01-23 22:42 UTC, alex-courtis commented on lua/nvim-tree/actions/node/buffer.lua
> +end
We can remove this NOP; we're moving away from this setup pattern anyway.

2025-01-23 22:42 UTC, alex-courtis commented on lua/nvim-tree/actions/node/buffer.lua
> +  M.delete_buffer("delete", node.absolute_path, opts)
This handles nil or partial node gracefully, however not a malformed node like `{ aaaabsolute_path = "foo" }`

That's OK - garbage in, garbage out.

2025-01-23 23:14 UTC, GCrispino commented on lua/nvim-tree/actions/node/utils.lua
Oh yeah, we can remove this, I forgot to do so, sorry!

2025-01-23 23:15 UTC, GCrispino commented
> Looks like we have some newly deprecated nvim methods : https://github.com/nvim-tree/nvim-tree.lua/actions/runs/12939265657/job/36091177064?pr=3040
> 
> I'll resolve them on master and merge.

@alex-courtis all good for me 🫡 ! Thanks for jumping in and resolving these 🙏🏼

2025-01-25 01:45 UTC, alex-courtis approved these changes
Many thanks for the fantastic addition

2025-01-25 01:47 UTC, merged

2025-01-25 02:01 UTC, GCrispino commented
> Many thanks for the fantastic addition

Thanks for that, and for assisting here! Would love to contribute again if there are any good opportunities for newcomers

2025-01-25 02:38 UTC, alex-courtis commented
> > Many thanks for the fantastic addition
> 
> Thanks for that, and for assisting here! Would love to contribute again if there are any good opportunities for newcomers

It's a pleasure to work with you and it'd be great to have another team member on board.

There's a [PR Please label](https://github.com/nvim-tree/nvim-tree.lua/issues?q=is%3Aissue%20state%3Aopen%20label%3A%22PR%20please%22%20sort%3Aupdated-desc) on many features / bugs - issues that we just don't have the bandwidth for.

Alternatively, there's a [larger project for Multiple Instances](https://github.com/nvim-tree/nvim-tree.lua/issues/2255) under way. [This task on the Project Board](https://github.com/orgs/nvim-tree/projects/1/views/1?pane=issue&itemId=85753418&issue=nvim-tree%7Cnvim-tree.lua%7C2988) would be a good start - it's got a clear goal and definition of done.

2025-01-25 02:42 UTC, alex-courtis commented
Added you as a project member so that you can push branches, review PRs, take tasks etc.

2025-01-25 14:20 UTC, GCrispino commented
> It's a pleasure to work with you and it'd be great to have another team member on board.

Thank you! Likewise, it was a pleasure to contribute :)

> There's a [PR Please label](https://github.com/nvim-tree/nvim-tree.lua/issues?q=is%3Aissue%20state%3Aopen%20label%3A%22PR%20please%22%20sort%3Aupdated-desc) on many features / bugs - issues that we just don't have the bandwidth for.
> 
> Alternatively, there's a [larger project for Multiple Instances](https://github.com/nvim-tree/nvim-tree.lua/issues/2255) under way. [This task on the Project Board](https://github.com/orgs/nvim-tree/projects/1/views/1?pane=issue&itemId=85753418&issue=nvim-tree%7Cnvim-tree.lua%7C2988) would be a good start - it's got a clear goal and definition of done.

Oh, nice! I think I'll pick up a bug so I get a bit more familiar with the project and Lua, as I'm not too familiar with the language and writing good code on it.
The Multiple Instances project sounds exciting!

2025-01-25 14:20 UTC, GCrispino commented
> Added you as a project member so that you can push branches, review PRs, take tasks etc.

Oh and of course, thanks for this! This is much appreciated :)